import type { Quest } from './types'

export const QUESTS: Quest[] = [
  // ── SOLO ──────────────────────────────────────────────────────────────────
  {
    id: 'sq-001',
    title: 'The Hidden Trail',
    description: 'Find and explore a local trail you\'ve never visited.',
    lore: 'Every path holds secrets for those brave enough to wander off the beaten track.',
    difficulty: 'Easy', category: 'Outdoor', mode: ['solo','duo','group'],
    xp: 100, icon: '🌿', tags: ['nature','walking'], repeatable: false,
    duration: 60, moods: ['chill','adventurous','curious'],
  },
  {
    id: 'sq-002',
    title: 'Talk to a Stranger',
    description: 'Strike up a conversation with someone you\'ve never met and learn one surprising fact about them.',
    lore: 'Every soul carries a story the world has never heard.',
    difficulty: 'Medium', category: 'Social', mode: ['solo'],
    xp: 120, icon: '🗣️', tags: ['social','brave'], repeatable: true,
    duration: 15, moods: ['social','adventurous'],
  },
  {
    id: 'sq-003',
    title: 'The Blind Bite',
    description: 'Eat something you\'ve never tried before — no googling, no research. Pure courage.',
    lore: 'The oracle says your destiny smells vaguely of spice.',
    difficulty: 'Easy', category: 'Food', mode: ['solo','duo','group'],
    xp: 80, icon: '🍽️', tags: ['food','brave'], repeatable: false,
    duration: 30, moods: ['chaotic','curious','adventurous'],
  },
  {
    id: 'sq-004',
    title: 'The Phonestack Pact',
    description: 'Sit somewhere beautiful for 20 minutes with your phone face-down. No peeking.',
    lore: 'Even legendary heroes needed to sit quietly and stare at a tree sometimes.',
    difficulty: 'Easy', category: 'Mindfulness', mode: ['solo','duo','group'],
    xp: 70, icon: '🍃', tags: ['mindfulness','stillness'], repeatable: true,
    duration: 20, moods: ['chill'],
  },
  {
    id: 'sq-005',
    title: 'Polyglot\'s Greeting',
    description: 'Learn to say "hello" in 5 different languages and use them all before sundown.',
    lore: 'The ancient linguist-mages said: a greeting opens every door.',
    difficulty: 'Medium', category: 'Learning', mode: ['solo'],
    xp: 150, icon: '🌍', tags: ['languages','social'], repeatable: false,
    duration: 45, moods: ['curious','social'],
  },
  {
    id: 'sq-006',
    title: 'The Oldest Stone',
    description: 'Find the oldest building or structure in your neighbourhood. Document it.',
    lore: 'History whispers from walls if you know how to listen.',
    difficulty: 'Hard', category: 'Outdoor', mode: ['solo','duo'],
    xp: 200, icon: '🏛️', tags: ['history','explore'], repeatable: false,
    duration: 90, moods: ['curious','adventurous'],
  },
  {
    id: 'sq-007',
    title: 'Commuter Haiku',
    description: 'Write a haiku about your journey today. 5-7-5. No cheating.',
    lore: 'The great poet-wanderers wrote on napkins, ticket stubs, and receipts.',
    difficulty: 'Easy', category: 'Creative', mode: ['solo'],
    xp: 60, icon: '✍️', tags: ['writing','creative'], repeatable: true,
    duration: 10, moods: ['chill','creative'],
  },
  {
    id: 'sq-008',
    title: 'Memento Mori Dish',
    description: 'Recreate a dish entirely from memory. No recipe, no peeking. Serve with confidence.',
    lore: 'The ancient chefs cooked only from memory — and they were terrifying.',
    difficulty: 'Hard', category: 'Food', mode: ['solo','duo'],
    xp: 250, icon: '👨‍🍳', tags: ['cooking','memory'], repeatable: false,
    duration: 90, moods: ['creative','chaotic'],
  },
  {
    id: 'sq-009',
    title: 'The Spontaneous 30',
    description: 'Do something completely spontaneous in the next 30 minutes. You cannot plan it.',
    lore: 'Chaos is just adventure without an itinerary.',
    difficulty: 'Legendary', category: 'Outdoor', mode: ['solo','duo','group'],
    xp: 500, icon: '⚡', tags: ['spontaneous','chaos'], repeatable: false, timeLimit: 30,
    duration: 30, moods: ['chaotic','adventurous'],
  },
  {
    id: 'sq-010',
    title: 'Secondhand Treasure Hunt',
    description: 'Visit a thrift store or market and find the strangest object you can for under $5.',
    lore: 'Every cursed artefact begins as someone else\'s donation.',
    difficulty: 'Easy', category: 'Outdoor', mode: ['solo','duo','group'],
    xp: 90, icon: '🛒', tags: ['thrift','treasure'], repeatable: true,
    duration: 45, moods: ['curious','chaotic'],
  },
  {
    id: 'sq-011',
    title: 'The Sky Report',
    description: 'Lie on your back somewhere outside and watch clouds for 10 minutes. Describe three shapes you saw.',
    lore: 'Ancient navigators charted courses entirely by cloud formation. You\'re basically a sailor.',
    difficulty: 'Easy', category: 'Mindfulness', mode: ['solo','duo','group'],
    xp: 60, icon: '☁️', tags: ['sky','mindfulness'], repeatable: true,
    duration: 15, moods: ['chill'],
  },
  {
    id: 'sq-012',
    title: 'Midnight Sketch',
    description: 'Draw something from your immediate surroundings using only a single pen. No erasing.',
    lore: 'Da Vinci\'s most beloved sketches were done on the back of receipts.',
    difficulty: 'Medium', category: 'Creative', mode: ['solo'],
    xp: 130, icon: '✏️', tags: ['art','sketch'], repeatable: true,
    duration: 30, moods: ['creative','chill'],
  },
  {
    id: 'sq-013',
    title: 'The Sunrise Oath',
    description: 'Wake up before sunrise and be somewhere outside when it happens.',
    lore: 'The early wanderer catches the first light — and mild frostbite.',
    difficulty: 'Hard', category: 'Outdoor', mode: ['solo','duo'],
    xp: 300, icon: '🌅', tags: ['sunrise','nature'], repeatable: false,
    duration: 60, moods: ['adventurous','chill'],
  },
  {
    id: 'sq-014',
    title: 'Random Act of Art',
    description: 'Leave a small piece of art in a public place for a stranger to find.',
    lore: 'Magic grows when it\'s given freely.',
    difficulty: 'Medium', category: 'Creative', mode: ['solo','duo'],
    xp: 160, icon: '🎨', tags: ['art','kindness'], repeatable: true,
    duration: 45, moods: ['creative','social'],
  },
  {
    id: 'sq-015',
    title: 'The One-Mile Circle',
    description: 'Walk in a circle of exactly one mile around your current location. Note 5 things you\'ve never noticed.',
    lore: 'The smallest maps hide the greatest wonders.',
    difficulty: 'Easy', category: 'Outdoor', mode: ['solo','duo','group'],
    xp: 100, icon: '🔵', tags: ['walking','observation'], repeatable: true,
    duration: 30, moods: ['chill','curious'],
  },
  {
    id: 'sq-016',
    title: 'Skill Swap',
    description: 'Teach someone a skill you have. Any skill. Document the lesson.',
    lore: 'Knowledge shared is power doubled.',
    difficulty: 'Medium', category: 'Social', mode: ['solo'],
    xp: 180, icon: '🤝', tags: ['teaching','skills'], repeatable: true,
    duration: 60, moods: ['social','curious'],
  },
  {
    id: 'sq-017',
    title: 'Bookshop Oracle',
    description: 'Enter a bookshop, close your eyes, pick a book at random. Read the first page. Buy it if it hooks you.',
    lore: 'The books that choose you are always the most important ones.',
    difficulty: 'Easy', category: 'Learning', mode: ['solo'],
    xp: 90, icon: '📚', tags: ['books','random'], repeatable: true,
    duration: 30, moods: ['curious','chill','chaotic'],
  },
  {
    id: 'sq-018',
    title: 'The Phone-free Dinner',
    description: 'Eat an entire meal, alone or with others, with no phone on the table.',
    lore: 'The ancient feasts lasted days. No one checked their notifications.',
    difficulty: 'Medium', category: 'Mindfulness', mode: ['solo','duo','group'],
    xp: 120, icon: '🍷', tags: ['mindfulness','dinner'], repeatable: true,
    duration: 60, moods: ['chill','social'],
  },
  {
    id: 'sq-019',
    title: 'Compliment Sniper',
    description: 'Give 3 genuine, specific compliments to 3 different people. Watch their day change.',
    lore: 'A well-aimed kind word pierces any armour.',
    difficulty: 'Medium', category: 'Social', mode: ['solo'],
    xp: 140, icon: '🎯', tags: ['kindness','brave'], repeatable: true,
    duration: 30, moods: ['social','adventurous'],
  },
  {
    id: 'sq-020',
    title: 'The Reverse Tourist',
    description: 'Be a tourist in your own city: take 5 gloriously cheesy tourist photos at places locals ignore.',
    lore: 'The locals never look up. The tourists never look down. Be both.',
    difficulty: 'Easy', category: 'Outdoor', mode: ['solo','duo','group'],
    xp: 110, icon: '📸', tags: ['photo','explore'], repeatable: true,
    duration: 60, moods: ['chaotic','curious','adventurous'],
  },
  {
    id: 'sq-021',
    title: 'NPC Mode',
    description: 'Sit in a café and invent detailed secret backstories for 5 strangers. Write them down.',
    lore: 'To you they\'re extras. To themselves they\'re the protagonist. Both are true.',
    difficulty: 'Easy', category: 'Creative', mode: ['solo','duo'],
    xp: 90, icon: '☕', tags: ['writing','people-watching'], repeatable: true,
    duration: 30, moods: ['curious','creative','chill'],
  },
  {
    id: 'sq-022',
    title: 'The Forbidden Recipe',
    description: 'Combine two foods that should never meet. Cook it. Eat at least three bites.',
    lore: 'The alchemists were just chefs with no fear of judgement.',
    difficulty: 'Hard', category: 'Food', mode: ['solo','duo','group'],
    xp: 220, icon: '🧪', tags: ['cooking','chaos'], repeatable: true,
    duration: 45, moods: ['chaotic'],
  },
  {
    id: 'sq-023',
    title: 'Left Turn Only',
    description: 'Go for a walk taking ONLY left turns for 20 minutes. See where the spiral takes you.',
    lore: 'The labyrinth was never a prison. It was a dance.',
    difficulty: 'Easy', category: 'Outdoor', mode: ['solo','duo'],
    xp: 80, icon: '↪️', tags: ['walking','random'], repeatable: true,
    duration: 20, moods: ['chaotic','curious'],
  },
  {
    id: 'sq-024',
    title: 'Time Traveler\'s Letter',
    description: 'Write a letter to yourself 10 years from now. Seal it. Hide it somewhere you\'ll forget.',
    lore: 'The future you is already waiting to read it.',
    difficulty: 'Medium', category: 'Creative', mode: ['solo'],
    xp: 150, icon: '⏳', tags: ['writing','future'], repeatable: false,
    duration: 30, moods: ['chill','creative'],
  },
  {
    id: 'sq-025',
    title: 'Silent Disco of One',
    description: 'Put on headphones in a public place and dance to one full song. Commit completely.',
    lore: 'The bards of old performed for kings. You perform for pigeons. Same energy.',
    difficulty: 'Legendary', category: 'Social', mode: ['solo'],
    xp: 450, icon: '🕺', tags: ['brave','chaos'], repeatable: false,
    duration: 10, moods: ['chaotic','adventurous'],
  },
  {
    id: 'sq-026',
    title: 'The Great Barter',
    description: 'Start with a paperclip-tier object. Trade it up 3 times with 3 different people.',
    lore: 'A kingdom was once won with a single red paperclip. Probably.',
    difficulty: 'Legendary', category: 'Social', mode: ['solo','group'],
    xp: 550, icon: '🔄', tags: ['trading','social','brave'], repeatable: false,
    duration: 120, moods: ['social','chaotic','adventurous'],
  },
  {
    id: 'sq-027',
    title: 'The 5-Song Sprint',
    description: 'Pick 5 high-energy songs. Declutter and clean as much as humanly possible before they end.',
    lore: 'The hero\'s montage requires no gym. Only a playlist.',
    difficulty: 'Easy', category: 'Mindfulness', mode: ['solo'],
    xp: 85, icon: '🧹', tags: ['home','energy'], repeatable: true,
    duration: 20, moods: ['chaotic','chill'],
  },
  {
    id: 'sq-028',
    title: 'Menu Roulette',
    description: 'At any eatery, order the 7th item on the menu. No substitutions. No mercy.',
    lore: 'The number 7 is lucky. The 7th menu item is... a gamble.',
    difficulty: 'Easy', category: 'Food', mode: ['solo','duo','group'],
    xp: 95, icon: '🎰', tags: ['food','random'], repeatable: true,
    duration: 45, moods: ['chaotic','curious'],
  },
  {
    id: 'sq-029',
    title: 'Ghost Mode',
    description: 'A full day with zero social media. Vanish. Let the timeline wonder.',
    lore: 'The strongest magic is the unread notification.',
    difficulty: 'Hard', category: 'Mindfulness', mode: ['solo'],
    xp: 280, icon: '👻', tags: ['digital-detox','willpower'], repeatable: true,
    duration: 480, moods: ['chill'],
  },
  {
    id: 'sq-030',
    title: 'Pen Pal Revival',
    description: 'Message someone you haven\'t spoken to in 3+ years. Ask them one real question.',
    lore: 'Old bridges don\'t burn. They just wait.',
    difficulty: 'Medium', category: 'Social', mode: ['solo'],
    xp: 160, icon: '💌', tags: ['reconnect','brave'], repeatable: true,
    duration: 15, moods: ['social','chill'],
  },
  {
    id: 'sq-031',
    title: 'Museum Speedrun',
    description: 'Enter any museum or gallery. You have 30 minutes to find the single weirdest thing in it.',
    lore: 'Somewhere in every collection hides one object that makes no sense. Find it.',
    difficulty: 'Medium', category: 'Learning', mode: ['solo','duo','group'],
    xp: 140, icon: '🏺', tags: ['culture','speedrun'], repeatable: true, timeLimit: 30,
    duration: 30, moods: ['curious','chaotic'],
  },
  {
    id: 'sq-032',
    title: 'The Sunset Chase',
    description: 'Find the best possible viewpoint you can reach before the sun goes down. Race it.',
    lore: 'The sun waits for no one. That\'s the whole point.',
    difficulty: 'Medium', category: 'Outdoor', mode: ['solo','duo','group'],
    xp: 170, icon: '🌇', tags: ['nature','race'], repeatable: true,
    duration: 60, moods: ['adventurous','chill'],
  },
  {
    id: 'sq-033',
    title: 'One-Word Poetry Slam',
    description: 'Ask 5 people for one random word each. Write a poem using all 5. Read it aloud to someone.',
    lore: 'The muses speak through strangers. Mostly nonsense, occasionally genius.',
    difficulty: 'Hard', category: 'Creative', mode: ['solo','group'],
    xp: 240, icon: '🎤', tags: ['writing','social','brave'], repeatable: true,
    duration: 60, moods: ['creative','social','chaotic'],
  },

  // ── COUPLES (duo) ─────────────────────────────────────────────────────────
  {
    id: 'dq-001',
    title: 'The First Date Remake',
    description: 'Recreate your first date together entirely from memory. Every detail counts.',
    lore: 'Time is a circle. Love is a loop.',
    difficulty: 'Medium', category: 'Social', mode: ['duo'],
    xp: 200, icon: '💑', tags: ['couples','memory','romance'], repeatable: false,
    duration: 120, moods: ['chill','social'],
  },
  {
    id: 'dq-002',
    title: 'Portrait Without Looking',
    description: 'Each of you draws a portrait of the other without looking at your paper. No peeking. Frame the results.',
    lore: 'The truest portraits are drawn with the eyes closed.',
    difficulty: 'Easy', category: 'Creative', mode: ['duo'],
    xp: 100, icon: '🎭', tags: ['art','couples'], repeatable: true,
    duration: 20, moods: ['creative','chaotic','chill'],
  },
  {
    id: 'dq-003',
    title: 'The Unknown Neighbourhood',
    description: 'Navigate to a part of your city neither of you has visited. No destination — just wander for an hour.',
    lore: 'Adventure is a place you haven\'t mapped yet.',
    difficulty: 'Medium', category: 'Outdoor', mode: ['duo'],
    xp: 180, icon: '🗺️', tags: ['explore','couples'], repeatable: true,
    duration: 90, moods: ['adventurous','curious'],
  },
  {
    id: 'dq-004',
    title: 'Cuisine of the Unknown',
    description: 'Cook a meal from a country neither of you has eaten food from. No shortcuts.',
    lore: 'The ancient spice traders said: cook what you don\'t know, learn who you are.',
    difficulty: 'Hard', category: 'Food', mode: ['duo'],
    xp: 280, icon: '🌶️', tags: ['cooking','couples','culture'], repeatable: false,
    duration: 120, moods: ['curious','creative'],
  },
  {
    id: 'dq-005',
    title: 'The Admiration Pact',
    description: 'Tell each other 3 things you genuinely admire about them. Then do one thing together that celebrates one of those traits.',
    lore: 'Even the mightiest heroes need to be reminded of their power.',
    difficulty: 'Legendary', category: 'Social', mode: ['duo'],
    xp: 500, icon: '💛', tags: ['connection','couples','deep'], repeatable: false,
    duration: 90, moods: ['chill','social'],
  },
  {
    id: 'dq-006',
    title: 'The Silence Walk',
    description: 'Go for a 20-minute walk together in total silence. No phones. Communicate only with gestures.',
    lore: 'The oldest form of communication predates language.',
    difficulty: 'Medium', category: 'Mindfulness', mode: ['duo'],
    xp: 150, icon: '🤫', tags: ['silence','connection'], repeatable: true,
    duration: 20, moods: ['chill'],
  },
  {
    id: 'dq-007',
    title: 'Swap & Tell',
    description: 'Each of you introduces the other to one thing you love (music, film, book, place). Engage with it together.',
    lore: 'Shared worlds are built one exchange at a time.',
    difficulty: 'Easy', category: 'Social', mode: ['duo'],
    xp: 120, icon: '🔄', tags: ['sharing','couples'], repeatable: true,
    duration: 60, moods: ['chill','curious','social'],
  },
  {
    id: 'dq-008',
    title: 'The Unplanned Picnic',
    description: 'Buy ingredients from the next shop you pass and find a green space. No planning allowed.',
    lore: 'The best feasts are improvised.',
    difficulty: 'Easy', category: 'Food', mode: ['duo'],
    xp: 130, icon: '🧺', tags: ['picnic','spontaneous','couples'], repeatable: true,
    duration: 90, moods: ['chill','adventurous','chaotic'],
  },
  {
    id: 'dq-009',
    title: 'Dream Map',
    description: 'Each draw a map of where you want to be in 5 years. Then compare them.',
    lore: 'Two maps, one journey.',
    difficulty: 'Hard', category: 'Creative', mode: ['duo'],
    xp: 320, icon: '🗺️', tags: ['future','couples','creative'], repeatable: false,
    duration: 60, moods: ['creative','chill'],
  },
  {
    id: 'dq-010',
    title: 'Accent Hour',
    description: 'Order food, run errands, exist — while both committing to terrible fake accents for one hour.',
    lore: 'The kingdom\'s greatest spies were just couples who refused to break character.',
    difficulty: 'Hard', category: 'Social', mode: ['duo'],
    xp: 260, icon: '🎭', tags: ['couples','chaos','brave'], repeatable: true,
    duration: 60, moods: ['chaotic','social'],
  },
  {
    id: 'dq-011',
    title: 'The Blindfold Taste Test',
    description: 'One of you blindfolded, the other picks 5 mystery foods. Guess them all. Then swap.',
    lore: 'Trust is letting someone feed you something while you cannot see it.',
    difficulty: 'Easy', category: 'Food', mode: ['duo'],
    xp: 110, icon: '🙈', tags: ['couples','food','trust'], repeatable: true,
    duration: 30, moods: ['chaotic','social','curious'],
  },

  // ── FRIENDS (group) ───────────────────────────────────────────────────────
  {
    id: 'gq-001',
    title: 'The Brave Order',
    description: 'Everyone at the table orders something they\'ve never tried. No one is exempt.',
    lore: 'The fellowship that eats strange food together stays together.',
    difficulty: 'Easy', category: 'Food', mode: ['group'],
    xp: 90, icon: '🍜', tags: ['food','brave','group'], repeatable: true,
    duration: 60, moods: ['social','curious','chaotic'],
  },
  {
    id: 'gq-002',
    title: 'Landmark of Legends',
    description: 'Find the most unusual landmark within walking distance. Group photo required.',
    lore: 'The hero\'s journey always ends with a photo.',
    difficulty: 'Medium', category: 'Outdoor', mode: ['group','duo'],
    xp: 160, icon: '📸', tags: ['photo','landmark','group'], repeatable: true,
    duration: 60, moods: ['adventurous','curious','social'],
  },
  {
    id: 'gq-003',
    title: 'The Skill Parliament',
    description: 'Each person teaches the group one skill they have, however small. You have 5 minutes each.',
    lore: 'In the ancient guilds, knowledge was the highest currency.',
    difficulty: 'Hard', category: 'Learning', mode: ['group'],
    xp: 260, icon: '🧠', tags: ['skills','teaching','group'], repeatable: false,
    duration: 60, moods: ['curious','social'],
  },
  {
    id: 'gq-004',
    title: 'The Collective Sketch',
    description: 'Pass a paper around. Each person adds one element to a group illustration without seeing what others drew.',
    lore: 'No great work of art was ever made alone. Or was it? Yes. But this one isn\'t.',
    difficulty: 'Medium', category: 'Creative', mode: ['group'],
    xp: 140, icon: '🖼️', tags: ['art','group','collaborative'], repeatable: true,
    duration: 30, moods: ['creative','chaotic','social'],
  },
  {
    id: 'gq-005',
    title: 'The Dice Destination',
    description: 'Roll a die to pick a direction. Walk for the number of minutes shown. Repeat twice.',
    lore: 'The dice gods are unpredictable but rarely boring.',
    difficulty: 'Legendary', category: 'Outdoor', mode: ['group','duo'],
    xp: 480, icon: '🎲', tags: ['random','explore','group'], repeatable: true,
    duration: 90, moods: ['chaotic','adventurous'],
  },
  {
    id: 'gq-006',
    title: 'The Group Confession',
    description: 'Everyone shares one thing they\'ve never admitted to the group. No judgement. All secrets stay in the quest.',
    lore: 'The truest bonds are forged in vulnerability.',
    difficulty: 'Hard', category: 'Social', mode: ['group'],
    xp: 280, icon: '🔐', tags: ['trust','deep','group'], repeatable: false,
    duration: 60, moods: ['social','chill'],
  },
  {
    id: 'gq-007',
    title: 'Scavenger Hunt: No Clues',
    description: 'Each person creates one riddle that leads to a location. Solve each other\'s riddles.',
    lore: 'The oldest games were also the most dangerous.',
    difficulty: 'Legendary', category: 'Outdoor', mode: ['group'],
    xp: 600, icon: '🔍', tags: ['puzzle','explore','group'], repeatable: false,
    duration: 120, moods: ['curious','adventurous','chaotic'],
  },
  {
    id: 'gq-008',
    title: 'The Potluck Challenge',
    description: 'Each person brings a dish from a cuisine assigned randomly by another member. No repeats.',
    lore: 'The great feasts of legend were always potlucks.',
    difficulty: 'Medium', category: 'Food', mode: ['group'],
    xp: 200, icon: '🥘', tags: ['cooking','food','group'], repeatable: true,
    duration: 120, moods: ['social','creative'],
  },
  {
    id: 'gq-009',
    title: 'Karaoke Russian Roulette',
    description: 'Everyone adds 2 songs to a hat. Each person must perform whatever they draw. Fully.',
    lore: 'The bards feared no ballad. Be the bard.',
    difficulty: 'Hard', category: 'Social', mode: ['group'],
    xp: 270, icon: '🎤', tags: ['music','brave','group'], repeatable: true,
    duration: 90, moods: ['chaotic','social'],
  },
  {
    id: 'gq-010',
    title: 'The Statue Game',
    description: 'In a public space, the group freezes in dramatic poses for 2 full minutes whenever one member yells "GALLERY!"',
    lore: 'Museums hate this one trick.',
    difficulty: 'Medium', category: 'Social', mode: ['group'],
    xp: 180, icon: '🗿', tags: ['chaos','public','group'], repeatable: true,
    duration: 45, moods: ['chaotic'],
  },
  {
    id: 'gq-011',
    title: 'Budget Banquet',
    description: 'Split up with $5 each. 20 minutes to buy one course. Reassemble and feast on the chaos menu.',
    lore: 'Five coins, five champions, one questionable banquet.',
    difficulty: 'Medium', category: 'Food', mode: ['group'],
    xp: 190, icon: '💸', tags: ['food','challenge','group'], repeatable: true, timeLimit: 20,
    duration: 60, moods: ['chaotic','social','adventurous'],
  },
]

export function getQuestsForMode(mode: 'solo' | 'duo' | 'group'): Quest[] {
  return QUESTS.filter(q => q.mode.includes(mode))
}

export function getQuestById(id: string): Quest | undefined {
  return QUESTS.find(q => q.id === id)
}
